kind: ImageStreamList
apiVersion: v1
metadata: {}
items:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: nodejs
      annotations:
        openshift.io/display-name: Node.js
    spec:
      tags:
        - name: '0.10'
          annotations:
            openshift.io/display-name: Node.js 0.10
            description: >-
              DEPRECATED: Build and run Node.js 0.10 applications on CentOS 7.
              For more information about using this builder image, including
              OpenShift considerations, see
              https://github.com/sclorg/s2i-nodejs-container/blob/master/0.10/README.md.
            iconClass: icon-nodejs
            tags: 'hidden,nodejs'
            supports: 'nodejs:0.10,nodejs:0.1,nodejs'
            version: '0.10'
            sampleRepo: 'https://github.com/openshift/nodejs-ex.git'
          from:
            kind: DockerImage
            name: 'openshift/nodejs-010-centos7:latest'
        - name: '4'
          annotations:
            openshift.io/display-name: Node.js 4
            description: >-
              Build and run Node.js 4 applications on CentOS 7. For more
              information about using this builder image, including OpenShift
              considerations, see
              https://github.com/sclorg/s2i-nodejs-container/blob/master/4/README.md.
            iconClass: icon-nodejs
            tags: 'builder,nodejs'
            supports: 'nodejs:4,nodejs'
            version: '4'
            sampleRepo: 'https://github.com/openshift/nodejs-ex.git'
          from:
            kind: DockerImage
            name: 'centos/nodejs-4-centos7:latest'
        - name: '6'
          annotations:
            openshift.io/display-name: Node.js 6
            description: >-
              Build and run Node.js 6 applications on CentOS 7. For more
              information about using this builder image, including OpenShift
              considerations, see
              https://github.com/goern/s2i-nodejs/blob/master/README.md
            iconClass: icon-nodejs
            tags: 'builder,nodejs'
            supports: 'nodejs:6,nodejs'
            version: '6'
            sampleRepo: 'https://github.com/openshift/nodejs-ex.git'
          from:
            kind: DockerImage
            name: 'goern-docker-registry.bintray.io/nodejs-6-centos7:latest'
